In [91]:
import numpy as np
arr=np.arange(5,10)

In [92]:
arr

array([5, 6, 7, 8, 9])

In [93]:
ar=np.arange(0,5).

In [94]:
ar

array([0, 1, 2, 3, 4])

In [99]:
arr

array([5, 6, 7, 8, 9])

In [102]:
arr**4

array([ 625, 1296, 2401, 4096, 6561], dtype=int32)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])