In [3]:
import numpy as np

In [15]:
l=[1,2,3,4]
arr=np.array(l)

In [16]:
arr


array([1, 2, 3, 4])

In [17]:
ma=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(ma)

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr=np.arange(2,10,0.00001)

In [49]:
arr=np.ones((3,4))

In [50]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [117]:
arr=np.linspace(1,100,10)

In [131]:
arr=np.random.randint(1,3,10)

In [132]:
arr

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 1])

In [133]:
arr= np.arange(25)

In [134]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [135]:
ranarr=np.random.randint(0,50,10)

In [136]:
ranarr

array([12, 40, 45,  3, 11, 37, 19, 45, 16, 22])

In [143]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [144]:
arr.max()

24

In [146]:
arr.min()

0

In [148]:
arr.argmax()

24

In [149]:
arr.argmin()

0

In [150]:
ranarr.argmin()

3

In [154]:
ranarr.shape

(10,)

In [155]:
arr.dtype

dtype('int32')